# Generated by Django 6.0.4 on 2026-05-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_ref', models.CharField(blank=True, help_text='Número del pedido relacionado, ej: PED-0023', max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Ajuste', 'Ajuste'), ('Devolucion', 'Devolución')], max_length=20)),
                ('subtipo', models.CharField(blank=True, choices=[('stock_inicial', 'Stock inicial'), ('reposicion', 'Reposición'), ('ajuste_manual', 'Ajuste manual'), ('devolucion_cliente', 'Devolución de cliente'), ('venta', 'Venta'), ('ajuste_salida', 'Ajuste salida')], max_length=30, null=True)),
                ('origen', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('cantidad', models.PositiveIntegerField(help_text='Siempre positivo. El tipo indica si es entrada o salida.')),
                ('stock_resultante', models.IntegerField(help_text='Stock del producto justo después de este movimiento.')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='PVP del producto al momento del movimiento.', max_digits=12, null=True)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_por', models.CharField(default='Sistema', help_text="Nombre del usuario o 'Sistema' si fue automático.", max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
