# Generated by Django 6.0.4 on 2026-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='pedido_ref',
            field=models.CharField(blank=True, help_text='Número del pedido relacionado, ej: PED-0001', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('stock_inicial', 'Stock inicial'), ('reposicion', 'Reposición'), ('ajuste_manual', 'Ajuste manual'), ('devolucion_cliente', 'Devolución de cliente'), ('venta', 'Venta'), ('cancelacion', 'Cancelación de pedido'), ('reserva', 'Reserva de pedido')], max_length=30, null=True),
        ),
    ]
