# Generated by Django 6.0.4 on 2026-05-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_kardex_pedido_ref_alter_kardex_subtipo'),
        ('usuarios', '0008_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Devolucion', 'Devolucion'), ('Devolucion solicitada', 'Devolucion solicitada'), ('Devuelto', 'Devuelto'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artesano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_artesano', to='usuarios.usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='usuarios.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
