# Generated by Django 6.0.4 on 2026-05-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pedido_detallepedido'),
        ('usuarios', '0010_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, default='Pakari Express', max_length=100),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='creado_por',
            field=models.CharField(default='Sistema', max_length=150),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='pedido_ref',
            field=models.CharField(blank=True, help_text='Número del pedido relacionado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='stock_resultante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='artesano',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'artesano'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_artesano', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Devolucion solicitada', 'Devolucion solicitada'), ('Devolucion aprobada', 'Devolucion aprobada'), ('Devolucion rechazada', 'Devolucion rechazada'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=30),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('respuesta_artesano', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='inventario.pedido')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
