# Generated by Django 6.0.4 on 2026-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_pedido_fecha_entrega_pedido_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pago pendiente', 'Pago pendiente'), ('Pago confirmado', 'Pago confirmado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Devolucion solicitada', 'Devolucion solicitada'), ('Devolucion aprobada', 'Devolucion aprobada'), ('Devolucion rechazada', 'Devolucion rechazada')], default='Pendiente', max_length=30),
        ),
    ]
