# Generated by Django 6.0.5 on 2026-09-09 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_favorito'),
        ('usuarios', '0016_passwordresettoken_favorito_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_inventario', to='usuarios.usuario'),
        ),
    ]
