# Generated by Django 6.0.4 on 2026-09-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_kardex_fecha_alter_pedido_estado'),
        ('inventario', '0006_favorito'),
    ]

    operations = [
    ]
