# Generated by Django 6.0.4 on 2026-09-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_merge_20260907_1852'),
        ('usuarios', '0018_remove_categoria_artesano_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_inventario', to='usuarios.usuario'),
        ),
    ]
