# Generated by Django 6.0.4 on 2026-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_favorito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('wompi', 'Wompi'), ('transferencia', 'Transferencia directa')], default='wompi', max_length=20),
        ),
    ]
