# Generated by Django 6.0.4 on 2026-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_pedido_comprobante_url_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
