# Generated by Django 6.0.4 on 2026-05-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_producto_valor_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('stock', 'Stock'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
