# Generated by Django 6.0.4 on 2026-05-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kardex',
        ),
    ]
