# Generated by Django 6.0.4 on 2026-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_delete_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_reservada',
            field=models.IntegerField(default=0, help_text='Unidades reservadas por pedidos en estado Pendiente.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_pvp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta al público.', max_digits=12, null=True),
        ),
    ]
