# Generated by Django 6.0.5 on 2026-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible en catálogo'),
        ),
    ]
