# Generated by Django 6.0.4 on 2026-05-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='artesano',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo': 'artesano'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='usuarios.usuario'),
        ),
    ]
