# Generated by Django 6.0.4 on 2026-08-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_categoria_artesano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
