# Generated by Django 6.0.4 on 2026-08-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_producto_imagen_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoIniciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('artesano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_recibidos', to='usuarios.usuario')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos_realizados', to='usuarios.usuario')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.producto')),
            ],
        ),
    ]
