# Generated by Django 6.0.4 on 2026-08-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_contactoiniciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.JSONField(blank=True, default=list, help_text='Lista de objetos {hex, nombre}, ej: [{"hex": "#b45309", "nombre": "Rojo"}]', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='producto',
            name='maneja_tallas',
            field=models.BooleanField(default=False, verbose_name='¿Maneja tallas?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tallas, ej: ["S", "M", "L"]', verbose_name='Tallas disponibles'),
        ),
    ]
