# Generated by Django 6.0.4 on 2026-09-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_producto_colores_producto_maneja_tallas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visitas',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha consultado el detalle de este producto.'),
        ),
    ]
