# Generated by Django 6.0.4 on 2026-09-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_producto_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_de', to='usuarios.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('cliente', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('cliente', 'producto')},
            },
        ),
    ]
