# Generated by Django 6.0.4 on 2026-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_passwordresettoken_favorito_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Visible en catálogo'),
        ),
    ]
