# Generated by Django 6.0.4 on 2026-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_categoria_artesano_usuario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pago_directo_banco',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Banco (o "Nequi")'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pago_directo_numero',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Número de cuenta o celular Nequi'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pago_directo_tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente'), ('Nequi', 'Nequi')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pago_directo_titular',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del titular de la cuenta'),
        ),
    ]
