# Generated by Django 6.0.4 on 2026-09-18 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_usuario_pago_directo_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario'),
        ),
    ]
