# Generated by Django 6.0.4 on 2026-09-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_notificacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cuenta activa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('artesano', 'Artesano'), ('admin', 'Administrador')], max_length=10),
        ),
    ]
